// src/app/api/save-inventory/route.ts
// Dev-only endpoint — writes studio state to src/data/inventory.ts
import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import { exportInventoryCode } from "@/components/studio/studioUtils";
import type { StudioSlot } from "@/components/studio/studioTypes";

const FILE_HEADER = `// src/data/inventory.ts
// ⚠️  This file is auto-generated by Studio Mode. Do not edit manually.
//     Make changes in the Studio, then click SAVE CHANGES.

import type { ShadowConfig } from "@/components/studio/studioTypes";

export interface OutfitItem {
  id: string;
  name: string;
  collection: string;
  colorway: string;
  price: string;
  type: "public" | "vault";
  dotPosition: string;
  lookbook?: string[];
}

export interface ModelSlot {
  id: string;
  position: string;
  scale: string;
  mobileScale: string;
  zIndex: number;
  imageSrc: string;
  outfit: OutfitItem[];
  shadow?: ShadowConfig;
}

`;

export async function POST(req: NextRequest) {
  // Dev-only guard — safe to deploy to production
  if (process.env.NODE_ENV !== "development") {
    return NextResponse.json(
      { ok: false, error: "Only available in development" },
      { status: 403 }
    );
  }

  let slots: StudioSlot[];
  try {
    const body = await req.json();
    if (!body || !Array.isArray(body.slots)) {
      return NextResponse.json(
        { ok: false, error: "Missing or invalid slots array" },
        { status: 400 }
      );
    }
    slots = body.slots as StudioSlot[];
  } catch {
    return NextResponse.json(
      { ok: false, error: "Invalid JSON body" },
      { status: 400 }
    );
  }

  try {
    const inventoryBody = exportInventoryCode(slots);
    if (!inventoryBody) {
      return NextResponse.json(
        { ok: false, error: "exportInventoryCode returned empty output" },
        { status: 500 }
      );
    }

    const fileContent = FILE_HEADER + inventoryBody + "\n";
    const filePath = path.join(process.cwd(), "src", "data", "inventory.ts");
    fs.writeFileSync(filePath, fileContent, "utf-8");

    return NextResponse.json({ ok: true });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ ok: false, error: message }, { status: 500 });
  }
}
