// src/data/inventory.ts
// ⚠️  This file is auto-generated by Studio Mode. Do not edit manually.
//     Make changes in the Studio, then click SAVE CHANGES.

import type { ShadowConfig } from "@/components/studio/studioTypes";

export interface OutfitItem {
  id: string;
  name: string;
  collection: string;
  colorway: string;
  price: string;
  type: "public" | "vault";
  dotPosition: string;
  lookbook?: string[];
}

export interface ModelSlot {
  id: string;
  position: string;
  scale: string;
  mobileScale: string;
  zIndex: number;
  imageSrc: string;
  outfit: OutfitItem[];
  shadow?: ShadowConfig;
}

export const MODEL_INVENTORY: ModelSlot[] = [
  {
    id: "lounge-model",
    // displayName: "Angel"
    position: "left-[19.5%] md:left-[19.5%] bottom-[5.1%] md:bottom-[5.1%]",
    scale: "md:scale-[0.85]",
    mobileScale: "scale-[0.85]",
    zIndex: 30,
    imageSrc: "/models/Angel/Angel-pro-lit.png",
    outfit: [
      {
        id: "lounge-showstopper",
        name: "The Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$1,200",
        type: "public",
        dotPosition: "top-[30.0%] left-[85.0%]",
        lookbook: [],
      },
      {
        id: "lounge-heartbreaker",
        name: "The Heartbreaker",
        collection: "The Constable",
        colorway: "Dark Grey",
        price: "$1,400",
        type: "vault",
        dotPosition: "top-[50.0%] left-[45.0%]",
        lookbook: [],
      },
    ],
    shadow: { offsetX: 0, offsetY: 8, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
  {
    id: "center-model",
    // displayName: "Center"
    position: "left-[34.2%] md:left-[34.2%] bottom-[16.4%] md:bottom-[16.4%]",
    scale: "md:scale-[0.70]",
    mobileScale: "scale-[0.70]",
    zIndex: 29,
    imageSrc: "/model-center.png",
    outfit: [
      {
        id: "center-showstopper",
        name: "The Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$1,500",
        type: "public",
        dotPosition: "top-[30.0%] left-[57.4%]",
        lookbook: [],
      },
      {
        id: "center-heartbreaker",
        name: "The Heartbreaker",
        collection: "The Constable",
        colorway: "Dark Grey",
        price: "$1,600",
        type: "vault",
        dotPosition: "top-[45.0%] left-[40.0%]",
        lookbook: [],
      },
    ],
    shadow: { offsetX: 0, offsetY: 8, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
  {
    id: "vault-model",
    // displayName: "Vault"
    position: "left-[24.3%] md:left-[24.3%] bottom-[9.3%] md:bottom-[9.3%]",
    scale: "md:scale-[0.84]",
    mobileScale: "scale-[0.84]",
    zIndex: 20,
    imageSrc: "/model-vault.png",
    outfit: [
      {
        id: "vault-showstopper",
        name: "The Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$980",
        type: "public",
        dotPosition: "top-[35.0%] left-[51.6%]",
        lookbook: [],
      },
      {
        id: "vault-heartbreaker",
        name: "The Heartbreaker",
        collection: "The Constable",
        colorway: "Dark Grey",
        price: "$1,100",
        type: "vault",
        dotPosition: "top-[47.0%] left-[42.0%]",
        lookbook: [],
      },
    ],
    shadow: { offsetX: 0, offsetY: 8, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
  {
    id: "rack-model",
    // displayName: "Rack"
    position: "left-[63.4%] md:left-[63.4%] bottom-[8.0%] md:bottom-[8.0%]",
    scale: "md:scale-[0.83]",
    mobileScale: "scale-[0.83]",
    zIndex: 30,
    imageSrc: "/model-rack.png",
    outfit: [
      {
        id: "rack-showstopper",
        name: "The Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$1,100",
        type: "public",
        dotPosition: "top-[58.0%] left-[88.0%]",
        lookbook: [],
      },
      {
        id: "rack-heartbreaker",
        name: "The Heartbreaker",
        collection: "The Constable",
        colorway: "Dark Grey",
        price: "$1,300",
        type: "vault",
        dotPosition: "top-[50.0%] left-[40.0%]",
        lookbook: [],
      },
    ],
    shadow: { offsetX: 0, offsetY: 8, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
];
