// src/data/inventory.ts
// ⚠️  This file is auto-generated by Studio Mode. Do not edit manually.
//     Make changes in the Studio, then click "Copy Production Config" and paste to Claude.

import type { ShadowConfig, LookbookItem, FilterDimension, AccessType } from "@/components/studio/studioTypes";

export interface OutfitItem {
  id: string;
  name: string;
  collection: string;
  colorway: string;
  /** Price as a display string, e.g. "$179" */
  price: string;
  type: AccessType;
  dotPosition: string;
  lookbook?: LookbookItem[];
  filterDimensions?: FilterDimension[];
  sizes: string[];
  sizeChart?: Record<string, { chest: string; length: string }>;
  materials?: string;
  story?: string;
  sizeGuide?: string;
}

export interface ModelSlot {
  id: string;
  displayName?: string;
  position: string;
  scale: string;
  mobileScale: string;
  zIndex: number;
  imageSrc: string;
  outfit: OutfitItem[];
  shadow?: ShadowConfig;
}

export const MODEL_INVENTORY: ModelSlot[] = [
  {
    id: "lounge-model",
    displayName: "Angel",
    position: "left-[30.0%] md:left-[30.0%] bottom-[14.9%] md:bottom-[14.9%]",
    scale: "md:scale-[0.94]",
    mobileScale: "scale-[0.94]",
    zIndex: 30,
    imageSrc: "/assets/models/Angel/Angel-Heart-Long.png",
    outfit: [
      {
        id: "lounge-showstopper",
        name: "Heartbreaker",
        collection: "The Constable",
        colorway: "Guilt Grey",
        price: "$179",
        type: "public",
        dotPosition: "top-[37.3%] left-[45.9%]",
        filterDimensions: [],
        lookbook: [],
        sizes: ["S", "M", "L", "XL", "XXL"],
        sizeChart: { "S": { chest: "38\"", length: "28\"" }, "M": { chest: "40\"", length: "29\"" }, "L": { chest: "42\"", length: "30\"" }, "XL": { chest: "44\"", length: "31\"" }, "XXL": { chest: "46\"", length: "32\"" } },
        story: "Built for the man who doesn't need to announce himself. The Constable's ivory Showstopper is the uniform of quiet authority.",
        materials: "98% Supima Cotton, 2% Elastane. Structured collar. Reinforced placket seam.",
        sizeGuide: "Cut close through the chest and tapered through the torso. If between sizes, size up.",
      },
    ],
    shadow: { offsetX: 0, offsetY: -18, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
  {
    id: "center-model",
    displayName: "Jerome",
    position: "left-[5.0%] md:left-[5.0%] bottom-[18.7%] md:bottom-[18.7%]",
    scale: "md:scale-[0.90]",
    mobileScale: "scale-[0.90]",
    zIndex: 29,
    imageSrc: "/assets/models/Jerome/Jerome-Show-Short.png",
    outfit: [
      {
        id: "center-showstopper",
        name: "Heartbreaker",
        collection: "The Constable",
        colorway: "Guilt Grey",
        price: "$129",
        type: "public",
        dotPosition: "top-[34.5%] left-[40.1%]",
        filterDimensions: [],
        lookbook: [],
        sizes: ["S", "M", "L", "XL", "XXL"],
        sizeChart: { "S": { chest: "38\"", length: "28\"" }, "M": { chest: "40\"", length: "29\"" }, "L": { chest: "42\"", length: "30\"" }, "XL": { chest: "44\"", length: "31\"" }, "XXL": { chest: "46\"", length: "32\"" } },
        story: "Built for the man who doesn't need to announce himself. The Constable's ivory Showstopper is the uniform of quiet authority.",
        materials: "98% Supima Cotton, 2% Elastane. Structured collar. Reinforced placket seam.",
        sizeGuide: "Cut close through the chest and tapered through the torso. If between sizes, size up.",
      },
    ],
    shadow: { offsetX: 0, offsetY: -18, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
  {
    id: "vault-model",
    displayName: "Jack",
    position: "left-[51.9%] md:left-[51.9%] bottom-[20.5%] md:bottom-[20.5%]",
    scale: "md:scale-[0.85]",
    mobileScale: "scale-[0.85]",
    zIndex: 20,
    imageSrc: "/assets/models/Jack/Jack-Show-Long.png",
    outfit: [
      {
        id: "vault-showstopper",
        name: "Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$179",
        type: "public",
        dotPosition: "top-[34.8%] left-[44.8%]",
        filterDimensions: [],
        lookbook: [],
        sizes: ["S", "M", "L", "XL", "XXL"],
        sizeChart: { "S": { chest: "38\"", length: "28\"" }, "M": { chest: "40\"", length: "29\"" }, "L": { chest: "42\"", length: "30\"" }, "XL": { chest: "44\"", length: "31\"" }, "XXL": { chest: "46\"", length: "32\"" } },
        story: "Built for the man who doesn't need to announce himself. The Constable's ivory Showstopper is the uniform of quiet authority.",
        materials: "98% Supima Cotton, 2% Elastane. Structured collar. Reinforced placket seam.",
        sizeGuide: "Cut close through the chest and tapered through the torso. If between sizes, size up.",
      },
    ],
    shadow: { offsetX: -28, offsetY: -18, scaleX: 0.90, scaleY: 0.080, opacity: 0.35, blur: 14 },
  },
  {
    id: "rack-model",
    displayName: "Ethan",
    position: "right-[1.9%] md:right-[1.9%] bottom-[18.2%] md:bottom-[18.2%]",
    scale: "md:scale-[0.91]",
    mobileScale: "scale-[0.91]",
    zIndex: 30,
    imageSrc: "/assets/models/Ethan/Ethan-Heart-Short.png",
    outfit: [
      {
        id: "rack-showstopper",
        name: "Showstopper",
        collection: "The Constable",
        colorway: "Ivory",
        price: "$129",
        type: "public",
        dotPosition: "top-[34.4%] left-[57.2%]",
        filterDimensions: [],
        lookbook: [],
        sizes: ["S", "M", "L", "XL", "XXL"],
        sizeChart: { "S": { chest: "38\"", length: "28\"" }, "M": { chest: "40\"", length: "29\"" }, "L": { chest: "42\"", length: "30\"" }, "XL": { chest: "44\"", length: "31\"" }, "XXL": { chest: "46\"", length: "32\"" } },
        story: "Built for the man who doesn't need to announce himself. The Constable's ivory Showstopper is the uniform of quiet authority.",
        materials: "98% Supima Cotton, 2% Elastane. Structured collar. Reinforced placket seam.",
        sizeGuide: "Cut close through the chest and tapered through the torso. If between sizes, size up.",
      },
    ],
    shadow: { offsetX: 0, offsetY: 0, scaleX: 0.90, scaleY: 0.080, opacity: 0.45, blur: 14 },
  },
];
